name: Release latest

on:
    push:
        branches: [master, main]

jobs:
    buildLatest:
        uses: apify/apify-test-tools/.github/workflows/public_push-build-latest.yaml@master
        secrets: inherit
